// auth actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHECK_USER = 'CHECK_USER';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_ERROR = 'CHECK_USER_ERROR';
export const LOAD_USER_LIST = 'LOAD_USER_LIST';
export const LOAD_USER_LIST_SUCCESS = 'LOAD_USER_LIST_SUCCESS';
export const LOAD_USER_LIST_ERROR = 'LOAD_USER_LIST_ERROR';

// bookCategories Actions
export const FETCH_BOOK_CATEGORIES = 'FETCH_BOOK_CATEGORIES';

// bookList Actions
export const FETCH_BOOK_LIST = 'FETCH_BOOK_LIST';
export const FETCH_BOOK_LIST_SUCCESS = 'FETCH_BOOK_LIST_SUCCESS';
export const FETCH_BOOK_LIST_ERROR = 'FETCH_BOOK_LIST_ERROR';
export const UPDATE_BOOK_LIST_RATE_DATA = 'UPDATE_BOOK_LIST_RATE_DATA';

// bookItem Actions
export const FETCH_BOOK_ITEM = 'FETCH_BOOK_ITEM';
export const FETCH_BOOK_ITEM_SUCCESS = 'FETCH_BOOK_ITEM_SUCCESS';
export const FETCH_BOOK_ITEM_ERROR = 'FETCH_BOOK_ITEM_ERROR';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const RATE_ITEM = 'RATE_ITEM';
export const RATE_ITEM_SUCCESS = 'RATE_ITEM_SUCCESS';
export const RATE_ITEM_ERROR = 'RATE_ITEM_ERROR';
export const ASSIGN_BOOK = 'ASSIGN_BOOK';
export const ASSIGN_BOOK_SUCCESS = 'ASSIGN_BOOK_SUCCESS';
export const ASSIGN_BOOK_ERROR = 'ASSIGN_BOOK_ERROR';
export const UNASSIGN_BOOK = 'UNASSIGN_BOOK';
export const UNASSIGN_BOOK_SUCCESS = 'UNASSIGN_BOOK_SUCCESS';
export const UNASSIGN_BOOK_ERROR = 'UNASSIGN_BOOK_ERROR';


// filterActions
export const FILTER_BY_DATE = 'FILTER_BY_DATE';
export const FILTER_BY_RATE = 'FILTER_BY_RATE';
